### ISSUE TITLE
Training with VGG16 joblib ValueError

### ISSUE THREAD

**Issue by caocuong0306** [BichenWuUCB/squeezeDet#21]
Hi @BichenWuUCB ,everyone

I try to test ConvDet by training with VGG16. However, it seems joblib cannot load the weight from VGG_ILSVRC_16_layers_weights.pkl file. I got the following error.

I hope you can assist on this problem. If possible, please check with your program and .pkl file.

Thank you very much.

Traceback (most recent call last):
  File "./src/train.py", line 286, in <module>
    tf.app.run()
  File "/home/cuong/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./src/train.py", line 282, in main
    train()
  File "./src/train.py", line 114, in train
    model = VGG16ConvDet(mc, FLAGS.gpu)
  File "/home/cuong/squeezeDet/src/nets/vgg16_convDet.py", line 25, in __init__
    self._add_forward_graph()
  File "/home/cuong/squeezeDet/src/nets/vgg16_convDet.py", line 39, in _add_forward_graph
    self.caffemodel_weight = joblib.load(mc.PRETRAINED_MODEL_PATH)
  File "/home/cuong/anaconda/envs/tensorflow/lib/python2.7/site-packages/joblib/numpy_pickle.py", line 575, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/cuong/anaconda/envs/tensorflow/lib/python2.7/site-packages/joblib/numpy_pickle.py", line 507, in _unpickle
    obj = unpickler.load()
  File "/home/cuong/anaconda/envs/tensorflow/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/home/cuong/anaconda/envs/tensorflow/lib/python2.7/site-packages/joblib/numpy_pickle.py", line 340, in load_build
    self.stack.append(array_wrapper.read(self))
  File "/home/cuong/anaconda/envs/tensorflow/lib/python2.7/site-packages/joblib/numpy_pickle.py", line 183, in read
    array = self.read_array(unpickler)
  File "/home/cuong/anaconda/envs/tensorflow/lib/python2.7/site-packages/joblib/numpy_pickle.py", line 144, in read_array
    array.shape = self.shape
ValueError: total size of new array must be unchanged

**Comment by DeepAnonymous** [comment]
I try to re-install anaconda, tensorflow, and everything. But I still got the following error:

Traceback (most recent call last):
  File "./src/train.py", line 286, in <module>
    tf.app.run()
  File "/home/cuong/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./src/train.py", line 282, in main
    train()
  File "./src/train.py", line 114, in train
    model = VGG16ConvDet(mc, FLAGS.gpu)
  File "/home/cuong/squeezeDet/src/nets/vgg16_convDet.py", line 25, in __init__
    self._add_forward_graph()
  File "/home/cuong/squeezeDet/src/nets/vgg16_convDet.py", line 39, in _add_forward_graph
    self.caffemodel_weight = joblib.load(mc.PRETRAINED_MODEL_PATH)
  File "/home/cuong/anaconda2/envs/tensorflow/lib/python2.7/site-packages/joblib/numpy_pickle.py", line 575, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/cuong/anaconda2/envs/tensorflow/lib/python2.7/site-packages/joblib/numpy_pickle.py", line 507, in _unpickle
    obj = unpickler.load()
  File "/home/cuong/anaconda2/envs/tensorflow/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/home/cuong/anaconda2/envs/tensorflow/lib/python2.7/site-packages/joblib/numpy_pickle.py", line 340, in load_build
    self.stack.append(array_wrapper.read(self))
  File "/home/cuong/anaconda2/envs/tensorflow/lib/python2.7/site-packages/joblib/numpy_pickle.py", line 183, in read
    array = self.read_array(unpickler)
  File "/home/cuong/anaconda2/envs/tensorflow/lib/python2.7/site-packages/**joblib/numpy_pickle.py**", line 144, in read_array
    array.shape = self.shape
ValueError: cannot reshape array of size **14446518 into shape (4096,4096)**

Hope you can help @BichenWuUCB,

**Comment by caocuong0306** [comment]
I try to re-install anaconda, tensorflow, and everything. But I still got the following error:

Traceback (most recent call last):
File "./src/train.py", line 286, in 
tf.app.run()
File "/home/cuong/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
_sys.exit(main(_sys.argv[:1] + flags_passthrough))
File "./src/train.py", line 282, in main
train()
File "./src/train.py", line 114, in train
model = VGG16ConvDet(mc, FLAGS.gpu)
File "/home/cuong/squeezeDet/src/nets/vgg16_convDet.py", line 25, in init
self._add_forward_graph()
File "/home/cuong/squeezeDet/src/nets/vgg16_convDet.py", line 39, in _add_forward_graph
self.caffemodel_weight = joblib.load(mc.PRETRAINED_MODEL_PATH)
File "/home/cuong/anaconda2/envs/tensorflow/lib/python2.7/site-packages/joblib/numpy_pickle.py", line 575, in load
obj = _unpickle(fobj, filename, mmap_mode)
File "/home/cuong/anaconda2/envs/tensorflow/lib/python2.7/site-packages/joblib/numpy_pickle.py", line 507, in _unpickle
obj = unpickler.load()
File "/home/cuong/anaconda2/envs/tensorflow/lib/python2.7/pickle.py", line 864, in load
dispatchkey
File "/home/cuong/anaconda2/envs/tensorflow/lib/python2.7/site-packages/joblib/numpy_pickle.py", line 340, in load_build
self.stack.append(array_wrapper.read(self))
File "/home/cuong/anaconda2/envs/tensorflow/lib/python2.7/site-packages/joblib/numpy_pickle.py", line 183, in read
array = self.read_array(unpickler)
File "/home/cuong/anaconda2/envs/tensorflow/lib/python2.7/site-packages**/joblib/numpy_pickle.py**", line 144, in read_array
array.shape = self.shape
ValueError: cannot reshape array of size **14446518 into shape (4096,4096)**

Hope you can help @BichenWuUCB,

**Comment by caocuong0306** [comment]
It seems the VGG_ILSVRC_16_layers_weights.pkl provided with dropbox link is broken.
I dump VGG_ILSVRC_16_layers.caffemodel by myself and it works.

Thank you,
