### ISSUE TITLE
No module error

### ISSUE THREAD

**Issue by Zumbalamambo** [BichenWuUCB/squeezeDet#69]
Im getting the following error while trying to run your code from src folder. I ran like `python demo.py`

```
Traceback (most recent call last):
  File "C:/Users/Downloads/Compressed/squeezeDet-master/squeezeDet-master/src/demo.py", line 23, in <module>
    from config import *
  File "C:\Users\Downloads\Compressed\squeezeDet-master\squeezeDet-master\src\config\__init__.py", line 1, in <module>
    from kitti_model_config import kitti_model_config
ImportError: No module named 'kitti_model_config'
```

**Comment by r4ghu** [comment]
Replace `from kitti_model_config import kitti_model_config` with `from .kitti_model_config import kitti_model_config` . 

You will get some new errors similar to above and all of them can be resolved by keeping '.'

**Comment by MyAusweis** [comment]
I have the same error, and i tried to add . but the python said syntax error, i use windows 8 and python 3.5 to run it. how to solve it

**Comment by diganthp** [comment]
check the pull request, "Fix for python3"
