### ISSUE TITLE
optimizing NMS with TensorFlow

### ISSUE THREAD

**Issue by venuktan** [BichenWuUCB/squeezeDet#78]
I am working on an optimized version of NMS 
```      
      self.det_probs = tf.reduce_max(probs, 2, name='score')
      self.det_class = tf.argmax(probs, 2, name='class_idx')


    with tf.variable_scope("nms") as scope:
      # for label,idx in enumerate(tf.unique(det_class)):
      label = tf.constant(1, dtype=tf.int64)
      self.matched = tf.equal(tf.transpose(self.det_class), label)
      self.selected_index = tf.gather(tf.transpose(tf.where(self.matched, name="class_index")), indices=[0])
      self.scores = tf.gather(tf.transpose(self.det_probs),
                            indices=self.selected_index,
                            name="dets_{}".format(int(1)))[0]

      self.xmin_ymin_xmax_ymax = tf.concat([xmins, ymins, xmaxs, ymaxs],
                                             axis=0, name="xmin_ymin_xmax_ymax")

      self.nms_in_bbox = tf.concat([ymins, xmins, ymaxs, xmaxs], axis=0)

      self.nms_in = tf.gather(
          tf.transpose(self.nms_in_bbox)
          , indices=self.selected_index
        , name="nms_in")[0]

      self.nms_selected_idx = tf.image.non_max_suppression(boxes=self.nms_in,
                                                           scores=self.scores,
                                                           max_output_size=tf.constant(10),
                                                           name="post_nms_{}".format(int(1)))

      # self.nms_selection_bbox = tf.gather(self.xmin_ymin_xmax_ymax, self.nms_selected_idx, name="selected_bboxs")
      # self.nms_probs = tf.gather(self.det_probs, self.selected_index, name="probs")
      # self.nms_class = tf.gather_nd(self.det_class, [self.selected_index], name="class")


  def _add_loss_graph(self):
    """Define the loss operation."""
    mc = self.mc
```
I am trying to insert this code here https://github.com/BichenWuUCB/squeezeDet/blob/4c78fa350f9c11ab9a5b620e78286846a7ee66de/src/nn_skeleton.py#L284

I am getting the following error:
```
$ python src/demo.py --mode image --input_path ./data/sample.png --out_dir ./
2017-09-20 17:27:01.932032: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-20 17:27:01.932051: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-20 17:27:01.932056: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-20 17:27:01.932060: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "src/demo.py", line 252, in <module>
    tf.app.run()
  File "/Users/venuktangirala/anaconda/envs/py27sq/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "src/demo.py", line 247, in main
    image_demo()
  File "src/demo.py", line 210, in image_demo
    feed_dict={model.image_input:[input_image]})
  File "/Users/venuktangirala/anaconda/envs/py27sq/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/Users/venuktangirala/anaconda/envs/py27sq/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/venuktangirala/anaconda/envs/py27sq/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/Users/venuktangirala/anaconda/envs/py27sq/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: scores must be 1-D[2523,1]
	 [[Node: nms/post_nms_1 = NonMaxSuppression[iou_threshold=0.5, _device="/job:localhost/replica:0/task:0/cpu:0"](nms/strided_slice_1, nms/strided_slice, nms/Const_1)]]

Caused by op u'nms/post_nms_1', defined at:
  File "src/demo.py", line 252, in <module>
    tf.app.run()
  File "/Users/venuktangirala/anaconda/envs/py27sq/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "src/demo.py", line 247, in main
    image_demo()
  File "src/demo.py", line 174, in image_demo
    model = SqueezeDet(mc, FLAGS.gpu)
  File "/Users/venuktangirala/cyngn/squeezeDet/src/nets/squeezeDet.py", line 25, in __init__
    self._add_interpretation_graph()
  File "/Users/venuktangirala/cyngn/squeezeDet/src/nn_skeleton.py", line 308, in _add_interpretation_graph
    name="post_nms_{}".format(int(1)))
  File "/Users/venuktangirala/anaconda/envs/py27sq/lib/python2.7/site-packages/tensorflow/python/ops/gen_image_ops.py", line 649, in non_max_suppression
    iou_threshold=iou_threshold, name=name)
  File "/Users/venuktangirala/anaconda/envs/py27sq/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/Users/venuktangirala/anaconda/envs/py27sq/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/venuktangirala/anaconda/envs/py27sq/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): scores must be 1-D[2523,1]
	 [[Node: nms/post_nms_1 = NonMaxSuppression[iou_threshold=0.5, _device="/job:localhost/replica:0/task:0/cpu:0"](nms/strided_slice_1, nms/strided_slice, nms/Const_1)]]
```

**Comment by Jee-King** [comment]
I have same problem, could you give me some suggests.
